// Import necessary dependencies and types
import React from 'react';
import useSeatsStyles from './useSeats.style';
import cs from 'classnames';

/** Props for this component */
interface SeatsProps {}

/** Component that displays a confirmation message after purchase is successful*/
const Seats: React.FC<SeatsProps> = () => {
  const styles = useSeatsStyles();
  return (
    <div className={cs(styles.seats)}>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat)}></div>
      <div className={cs(styles.seat)}></div>
      <div className={cs(styles.seat)}></div>
      <div className={cs(styles.seat)}></div>
      <div className={cs(styles.seat)}></div>
      <div className={cs(styles.seat)}></div>
      <div className={cs(styles.seat)}></div>
      <div className={cs(styles.seat)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
      <div className={cs(styles.seat, styles.seatOccupied)}></div>
    </div>
  );
};

export default Seats;
